### ISSUE TITLE
marking 'actionable' abilities on cards

### ISSUE THREAD

**Issue by Casenhob** [guidokessels/xwing-data2#150]
I was wondering if cards which grand actionable abilities should be marked as 'actionable'. There are plenty of pilots, upgrades, conditions and damage cards that give extra actions to a ship, and an indication of this could help for some apps I guess

**Comment by mludowise** [comment]
I agree that I don’t think it’s worth the effort to encode the actions. My philosophy for developing DialVision is that any action is possible for a ship with the right pilot or upgrade card and it’s up to the users playing the game to enforce the rules. Even if we did decide on a way to encode actions on cards, FFG could come out with a new card that breaks some of the assumptions we made to encode the data.

Just my 2 cents as developer who consumes X-Wing data 😊

**Comment by Casenhob** [comment]
Well, I was just wondering who is the target of this library.
I like to think there is a variaty of reasons one would use it: card database to keep track of the cards you own; listbuilding tool; search library if you're looking for specific mechanic; stat tracker; list keeper during a game; ...

I think that for some of these it's reasonable to add an indication that a card gives an extra action. The same actually as an indication for a bonus attack, or some keywords, or....

Perhaps we could add keywords like focus if a card gives or needs focus, same for stress, lock, ion, ...

We can add any data we like, it will only benefit the user of this library. My first thought was action giving cards, but thinking about it a bit more, there is so much 'meta' data could (and in my opinion should) add.

**Comment by FreakyDug** [comment]
You're right that we can add any data we like, but don't forget that the more data we add, the greater the overhead on adding new cards to the system. I think the problem with adding metadata like you describe is that because we can't make it comprehensive or unambiguous (eg. is this card actionable because it has an *Action:* on it or because it gives you an action after a certain trigger, when does this card give you a focus) we'd be increasing the amount of work without actually benefitting anybody.

I think it's better to wait for use cases to present themselves and add data when it's feasible than to try and pre-empt them. I agree that it's important to consider all the tools that use it (I'm definitely guilty of only thinking about what R2-D7 can use from it), but we don't want to try and guess what potential future tools need, because we'll probably be wrong.
