### ISSUE TITLE
 Kare Kun or Karé Kun

### ISSUE THREAD

**Issue by infinityloop** [guidokessels/xwing-data2#161]
The card text saids Kare Kun but the wikipedia on her says Karé Kun. The accented character is minor but prevents basic string comparisons.

I wasn't sure if I should submit the change with a general consensus on how to deal with these cases.

**Comment by sirjorj** [comment]
I recently made this correction in my own data library.  I think this is because the Polish version of the card was the first to leak.

**Comment by davidhorm** [comment]
My vote is to write what the card shows (which is w/o the accent...which is even what the Polish version on the official app builder shows).
In the case where a new pilot named "¢@$ℏ ℳ0Ñ€¥" comes out, then I vote we still write the same characters for `pilots.name`, but have a new `pilots.translated_name` = "Cash Money"

**Comment by FreakyDug** [comment]
Hmm, this is tricky. If they mispelt a name we'd assume it was a mistake and use the correct name, and that is basically the same as what's happening here, except that they continue to mispell it in places they could fix it like the app. I guess we should match what's on the card, since that's the official name of the pilot in the game, even if it doesn't match her canon name.

**Comment by danrs** [comment]
This issue has been inactive for over a year and will be closed if there is no further activity before 15/09/2020.
