### ISSUE TITLE
SOC axe cost is 3, should be 4

### ISSUE THREAD

**Issue by chrisalleng** [guidokessels/xwing-data2#598]

**Comment by Radroggor** [comment]
It's done in last commits:
![image](https://user-images.githubusercontent.com/106243466/206121509-2b1590b1-42c0-412b-8e71-024b4f3d54a0.png)
You can close this issue.

**Comment by danrs** [comment]
@Radroggor in future, please link the [file](https://github.com/guidokessels/xwing-data2/blob/master/data/pilots/galactic-republic/v-19-torrent-starfighter.json) or [commit diff](https://github.com/guidokessels/xwing-data2/commit/ebdafb4112f3a02188adf63174f4415711b4aeb5) instead of a screenshot, as it makes it much faster for me to confirm the change.
