### ISSUE TITLE
SOC haor chall prototype is limited 1, should be 2

### ISSUE THREAD

**Issue by chrisalleng** [guidokessels/xwing-data2#599]

**Comment by danrs** [comment]
@Radroggor in future, please link the [file](https://github.com/guidokessels/xwing-data2/blob/master/data/pilots/separatist-alliance/vulture-class-droid-fighter.json) or [commit diff](https://github.com/guidokessels/xwing-data2/commit/b19b29d25e4925bcaa5ef33d5551f7739c79d034) instead of a screenshot, as it makes it much faster for me to confirm the change.
