### ISSUE TITLE
Delta 7B Aethersprite does not exist in translation

### ISSUE THREAD

**Issue by ToshioMagic** [guidokessels/xwing-data2#603]
I'm trying to use the project for RollBetter.gg. I have a few questions.

1. Is the translation.json file regenerated on each semver increment?
2. The delta 7b aethersprite does not show up in the translation.json file as I would expect. AMG treats it as a separate ship. There is a separate ship file for it in the source data. Is this an error? Should I expect to see a translation for it? My expectations are based on XWS coming from popular list builders that use the string`delta7baethersprite` as the ship identifier.
3. If I should not expect to see that string in the translation.json, how should I go about translating it when I see it using this project?

**Comment by danrs** [comment]
1. No, the translation file is manually neglected and is not actively maintained. The release process is outlined [here](https://github.com/guidokessels/xwing-data2#creating-a-release)
2. As above, the translations are old and outdated. They have not been touched since AMG changed the 7b from a config to a ship
3. I'm not aware of any projects which actually use that translation file (I assume that if it was under active use it would have active contributors). From an xwing-data2 perspective, the "correct" approach is probably to update the file with 7b and other recent changes. This work could be performed by yourself or other contributors - the active maintainers of this repo only have enough time for new card data entry, and we don't all have access to alternate-language cards.
