### ISSUE TITLE
Offer of almost completed quickbuild data

### ISSUE THREAD

**Issue by Kexikus** [guidokessels/xwing-data2#604]
I added all the missing quickbuilds (except for squads) for a local copy of this database that I used for a project of mine and hereby offer to have them added to this repo.
Unfortunately I don't know anything about committing stuff to GitHub so instead, I created this issue. I attached the edited .json files to this post. Feel free to add them.

I also fixed a few mistakes with the rebel quickbuilds. IIRC "Chewbacca" on the Millenium Falcon had the Resistance C-3PO equipped and there were some rebel quickbuilds that had upgrades of the same type separated, i.e., in two lists.

All in all, I added the quickbuilds from these expansions:
- TIE Inquisitor
- Skystrike Academy Pack
- TIE Heavy
- VT-49 Decimator
- Phoenix Squadron Pack
- Millenium Falcon
- A-Wing
- Ghost
- Pride of Mandalore
- Droid Tri Fighter
- Separatist Firespray
- HMP Gunship
- Nantex
- Rogue Class
- Eta-2
- LAAT
- V-Wing
- Clone Z-95
- Fugitives and Collaborators
- Punishing One
- M3-A Interceptor
- Hound's Tooth
- Razor Crest
- Fury of the First Order
- Xi-Class Shuttle
- Resistance Y-Wing
- Heralds of Hope

I also added all huge ships from both their expansions and the huge ship conversion kit and one Vulture Droid quickbuild that was missing.

[quick-builds.zip](https://github.com/guidokessels/xwing-data2/files/10797078/quick-builds.zip)

**Comment by danrs** [comment]
Creating a PR is a fairly straightforward process (and you can practice/study it [here](https://github.com/danrs/git-practice)). You'd just need to update the existing files with your modifications, push to github and then start a PR. I highly recommend taking the time to give it a go!

So in this case, what you would do is:
- [fork this repo on github](https://github.com/guidokessels/xwing-data2/fork)
- `git clone git@github.com:kexikus/xwing-data2.git`
- edit the files (eg `cp ~/Documents/quick-builds/* ~/xwing-data2/data/quick-builds`)
- `git commit -a` from within the repo, then type a commit message much like what you've written above
- `git push origin master` to push your changes to your github fork
- On your fork, open a [pull request](https://github.com/guidokessels/xwing-data2/pull/606) against this repo
- Guido or myself would review, ask you to fix any errors, and merge the PR. Done!
- optionally update your fork with the new changes from this upstream repo

In my case I'm pushing to a branch on this repo instead of my own fork, but otherwise it's the same process.

Closing this issue as it will be solved by https://github.com/guidokessels/xwing-data2/pull/606
