### ISSUE TITLE
Add "Has been Errata'd" data?

### ISSUE THREAD

**Issue by davidhorm** [guidokessels/xwing-data2#84]
Just realized that Proximity Mines got errata'd and I'll send a PR for that fix in a bit. But then that got me thinking, should we add some Errata Boolean property to the cards? Here's the use case:

I'm using the data to build my squad. Then I gather all the components and reread the cards only to see the text is different than the data from this repo. Now I can assume that the data has been errata'd, but I can also likely assume that the data is incorrect in this repro. Now I have to do some homework to figure out which is correct.

Personally I would be cool with just a Boolean. But when I was keeping my own data for 1.0 stuff, I did keep track of the original text just so I can compare. It was useful for when people were arguing about how a card worked, and I noticed they were referencing the original text. But things get weird with Saw's Renegades and Tie Reaper corrections since proton torpedoes are wrong in those packs, but correct in the conversion kits.

**Comment by izakman** [comment]
I can see having the original text being useful. Maybe have a "versions" key that contains an array of the previous texts. You can just test for the existence of that key then.

**Comment by izakman** [comment]
Maybe overkill as other values may never get changed, but the array could be objects which mimic the structure of the card with the previous values.

Say Ten Numb's text _and_ initiative changes, versions could store both original values:

```json
"versions": [
    {
        "initiative": 4,
        "ability": "While you defend or perform an attack, you may spend 1 stress token to change all of your [Focus] results to [Evade] or [Hit] results.",
    }
]
```

Or the B-Wing itself get its shields reduced:

```json
"versions": [
    {
        "stats": [
            { "type": "shields", "value": 4 }
        ]
    }
]
```

**Comment by danrs** [comment]
This issue has been inactive for over a year and will be closed if there is no further activity before 15/09/2020.

If you do wish to progress with this issue, I have the following thoughts:
- A date should be included with each version
- I don't see what value this adds to xwing-data2. In 2.0, erratas mostly are used to correct typographical errors rather than for balance reasons, so the pre-errata version of a card has very little value in terms of gameplay.
- If we start storing errata versions, the obvious next question is whether to store points history as well. I think errata history is less useful than points history. Whether storing points history is worthwhile is another question altogether.
